# GoReleaser already creates Botkube artifacts in the ./dist folder.
# To not override them during release, we use a different folder
dist: plugin-dist

before:
  hooks:
    - go mod download

builds:
  - id: helm
    main: cmd/executor/helm/main.go
    binary: executor_helm_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: &env
      - CGO_ENABLED=0
    goos: &goos
      - linux
      - darwin
    goarch: &goarch
      - amd64
      - arm64
    goarm: &goarm
      - 7

  - id: kubectl
    main: cmd/executor/kubectl/main.go
    binary: executor_kubectl_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: *env
    goos: *goos
    goarch: *goarch
    goarm: *goarm

  - id: kubernetes
    main: cmd/source/kubernetes/main.go
    binary: source_kubernetes_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: *env
    goos: *goos
    goarch: *goarch
    goarm: *goarm

  - id: kbcli
    main: cmd/kbcli/main.go
    binary: executor_kbcli_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: &env
      - CGO_ENABLED=0
    goos: &goos
      - linux
      - darwin
    goarch: &goarch
      - amd64
      - arm64
    goarm: &goarm
      - 7

snapshot:
  name_template: 'v{{ .Version }}'
